# MBL Models

Techniques used to impliment a memory-based learner are outlined in this section

## Model Theory
{Explanation of how mbl works with some pretty pictures, explain the package used}

## Making MBL Predictions
```{r eval=FALSE, echo=FALSE}
library(readr)
diag<- read_csv("Single_Lib/mbl_var.csv", col_types=cols())

library(knitr)
colnames(diag)<-c("","Spectral Matrix","Lab Data")
kable(diag[1:2, 1:3], align="c")
```

```{r eval=FALSE}
Xu <- predDat$spc
Yu <- sqrt(predDat[,property]) 
Yr <- sqrt(calib[,property])
Xr <- calib$spc


Xu <- Xu[!is.na(Yu),]
Yu <- Yu[!is.na(Yu)]
Xr <- Xr[!is.na(Yr),]
Yr <- Yr[!is.na(Yr)]
    ctrl <- mblControl(sm = 'pc', pcSelection = list('opc', 50),
                       valMethod = 'loc_crossval',center=TRUE,scale=FALSE,allowParallel=FALSE)
    mbl.sqrt <- mbl(Yr = Yr, Xr = Xr, Yu = Yu, Xu = Xu,
                    mblCtrl = ctrl,
                    dissUsage = 'none',
                    #k = seq(40, 100, by = 20),
                    k = seq(10, 20, by = 2),
                    method = 'pls', pls.c = 6)
    #save(mbl.sqrt, file= paste(savepath, savename,".RData", sep=""))
    
    #2- Applying the model
    #savepath <- paste("./Models/USGS/Geochem/Predictions/", sep="")
    #savename <- paste(property, modelType, fd, predDatName, paste("v",datname,sep=""), sep=".")
    predVals <- c(mbl.sqrt$results$Nearest_neighbours_40$pred)^2
    #predVals <- c(mbl.sqrt$results$Nearest_neighbours_14$pred)^2
  }
  
  #{option 2-- weighted to closer neighbors}
  if(TRUE){
    
    Xu <- predDat$spc
    Yu <- sqrt(predDat[,property]) 
    Yr <- sqrt(calib[,property])
    Xr <- calib$spc
    Xu <- Xu[!is.na(Yu),]
    Yu <- Yu[!is.na(Yu)]
    Xr <- Xr[!is.na(Yr),]
    Yr <- Yr[!is.na(Yr)]
    
    dmetric = "pls"
    diss2test <- seq(0.3, 1, by=0.1)
    kminmax <- c(10, nrow(calib$spc))
    rmethod <- "wapls1"
    pls.f <- c(minpls=3, maxpls=20)
    
    ctrl <- mblControl(sm = dmetric, pcSelection = list("opc", 50), valMethod = "NNv", 
                       returnDiss = TRUE, scaled = FALSE, center = TRUE)
    
    mbl.sqrt <- mbl(Yr = Yr, Xr = Xr, Xu = Xu, mblCtrl = ctrl, dissUsage = "none", k.diss = diss2test, k.range = kminmax, 
                    pls.c = pls.f, method = rmethod)
    
    idx.best.ca <- which.min(mbl.sqrt$nnValStats$st.rmse)
    best.kdiss.ca <- mbl.sqrt$nnValStats$k.diss[idx.best.ca]
    
    ## Get the predicted values for the validation set
    predVals <- c(getPredictions(mbl.sqrt)[, idx.best.ca])^2
  }
```
